Controllers/DadosController.cs
using Acesv.Models;
using Acesv2.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Acesvv.Controllers
{
    public class DadosController : Controller
    {
        private readonly BD _context;
        private readonly ChaveADMRequirement _chaveADMRequirement;

        public DadosController(BD dadosContext, ChaveADMRequirement chaveADMRequirement)
        {
            _context = dadosContext;
            _chaveADMRequirement = chaveADMRequirement;
        }

        public ActionResult DownloadRelatorio()
        {
            using (var db = new BD())
            {
                var dados = db.Dados.Include(d => d.Escola).ToList();

                Document doc = new Document();
                MemoryStream ms = new MemoryStream();
                PdfWriter writer = PdfWriter.GetInstance(doc, ms);

                doc.Open();

                var mapeamentoCampos = new Dictionary<string, string>
                {
                    { "Escolas", "EscolaId" },
                    { "Nome Completo", "NomeCompleto" },
                    { "Telefone", "Telefone" },
                    { "Placa", "Placa" },
                    { "Apelido", "Apelido" },
                    { "CPF", "Cpf" },
                    { "Data de Nascimento", "Data_Nascimento" },
                    { "Prefixo", "Prefixo" },
                    { "Bairros", "Bairros" },
                    { "Veículo", "Veiculo" },
                    { "Ano", "Ano" },
                    { "CNH", "Cnh" },
                    { "Categoria", "CategoriaSelecionada" },
                    { "Validade", "Validade" },
                    { "Endereço", "Endereco" },
                    { "Bairro", "Bairro" },
                    { "CEP", "Cep" },
                    { "Número", "Número" },
                    { "Complemento", "Complemento" },
                };

                var headerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.WHITE);
                var cellFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.BLACK);
                var headerBackgroundColor = new BaseColor(0, 156, 220);

                foreach (var dado in dados)
                {
                    PdfPTable table = new PdfPTable(2);
                    float[] columnWidths = new float[] { 2f, 4f };
                    table.SetWidths(columnWidths);

                    foreach (var colunaPersonalizada in mapeamentoCampos)
                    {
                        var nomeColuna = colunaPersonalizada.Key;
                        var nomePropriedade = colunaPersonalizada.Value;

                        string valor = nomePropriedade == "EscolaId" ? GetEscolasSelecionadas(dado.EscolaId) : GetValorCampo(dado, nomePropriedade);

                        PdfPCell headerCell = new PdfPCell(new Phrase(nomeColuna, headerFont));
                        headerCell.BackgroundColor = headerBackgroundColor;
                        table.AddCell(headerCell);

                        PdfPCell cell = new PdfPCell(new Phrase(valor, cellFont));
                        table.AddCell(cell);
                    }

                    doc.Add(table);
                    doc.NewPage();
                }

                doc.Close();

                byte[] pdfData = ms.ToArray();

                return File(pdfData, "application/pdf", "Dados.pdf");
            }
        }

        string GetValorCampo(object obj, string fieldName)
        {
            var propInfo = obj.GetType().GetProperty(fieldName);
            if (propInfo != null)
            {
                var value = propInfo.GetValue(obj, null);
                if (value != null)
                {
                    return value.ToString();
                }
            }
            return string.Empty;
        }

        string GetEscolasSelecionadas(List<int> escolaIds)
        {
            if (escolaIds == null)
            {
                return "Nenhuma escola encontrada";
            }

            var escolasSelecionadas = new List<string>();
            foreach (var escolaId in escolaIds)
            {
                var escola = _context.Escolas.Find(escolaId);
                if (escola != null)
                {
                    escolasSelecionadas.Add(escola.NomeEscola);
                }
            }
            return string.Join(", ", escolasSelecionadas);
        }

        public async Task<IActionResult> Index()
        {
            ChaveADMRequirement chaveAdm = new ChaveADMRequirement();
            if (!User.Identity.IsAuthenticated)
            {
                string returnUrl = "/Identity/Account/AccessDeniedLogin";
                return Redirect(returnUrl);
            }
            var userEmail = User.Identity.Name;
            string chaveADM = chaveAdm.Chama_ChaveADM(userEmail);
            if (chaveADM != "1")
            {
                string returnUrl = "/Identity/Account/AccessDenied?ReturnUrl=%2FDados";
                return Redirect(returnUrl);
            }

            var dados = await _context.Dados.Include(d => d.Escola).ToListAsync();

            foreach (var dado in dados)
            {
                if (dado.EscolaId != null && dado.EscolaId.Count > 0)
                {
                    var escolasSelecionadas = new List<string>();

                    foreach (var escolaId in dado.EscolaId)
                    {
                        var escola = await _context.Escolas.FindAsync(escolaId);
                        if (escola != null)
                        {
                            escolasSelecionadas.Add(escola.NomeEscola);
                        }
                    }

                    dado.EscolasSelecionadas = string.Join(", ", escolasSelecionadas);
                }
            }
            return View(dados);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Dados == null)
            {
                return NotFound();
            }

            var dados = await _context.Dados
                .Include(d => d.Escola)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dados == null)
            {
                return NotFound();
            }

            return View(dados);
        }

        public IActionResult Create()
        {
            var categorias = Enum.GetValues(typeof(Categoria))
                     .Cast<Categoria>()
                     .Select(c => new SelectListItem
                     {
                         Value = c.ToString(),
                         Text = c.ToString()
                     })
                     .ToList();

            ViewData["Categorias"] = categorias;
            ViewBag.Escolas = new MultiSelectList(_context.Escolas, "Id", "NomeEscola");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EscolaId,NomeCompleto,Telefone,Placa,Apelido,Cpf,Data_Nascimento,Prefixo,Bairros,Veiculo,Ano,Cnh,Categoria,CategoriaSelecionada,Validade,Endereco,Bairro,Cep,Número,Complemento")] Dados dados)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dados);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Escolas = new SelectList(_context.Escolas, "Id", "NomeEscola");

            return View(dados);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.ErrorMessage = "Nenhum registro foi encontrado.";
                return View("Error");
            }

            var dados = await _context.Dados.FindAsync(id);
            if (dados == null) { }

            var escolas = _context.Escolas.ToList();
            ViewBag.Escolas = escolas.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.NomeEscola,
                Selected = dados.EscolasSelecionadas != null && dados.EscolasSelecionadas.Contains(e.Id.ToString())
            }).ToList();

            var categorias = Enum.GetValues(typeof(Categoria))
                  .Cast<Categoria>()
                  .Select(c => new SelectListItem
                  {
                      Value = c.ToString(),
                      Text = c.ToString()
                  })
                  .ToList();

            ViewData["Categorias"] = categorias;
            return View(dados);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EscolaId,EscolasSelecionadas,NomeCompleto,Telefone,Placa,Apelido,Cpf,Data_Nascimento,Prefixo,Bairros,Veiculo,Ano,Cnh,CategoriaSelecionada,Validade,Endereco,Bairro,Cep,Número,Complemento")] Dados dados)
        {
            if (id != dados.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var escolasSelecionadas = dados.EscolaId ?? new List<int>();
                    dados.EscolasSelecionadas = string.Join(",", escolasSelecionadas);

                    _context.Update(dados);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DadosExists(dados.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var todasEscolas = await _context.Escolas.ToListAsync();

Views/EditarMotoristas/TelaDados.cshtml
@model IEnumerable<Acesv.Models.Dados>

    @using System.Linq;
    @using Microsoft.Data.SqlClient;
@{

    ViewData["Title"] = "Index";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dados</title>
    <link rel="stylesheet" href="/css/TelaDados.css">
</head>


<script>
    function searchTable() {
        var input = document.getElementById("searchInput");
        var filter = input.value.toLowerCase();
        var table = document.getElementById("pesquisarTransportador");
        var rows = table.getElementsByTagName("tr");

        for (var i = 0; i < rows.length; i++) {
            var clienteCell = rows[i].getElementsByTagName("td")[1];
            if (clienteCell) {
                var cliente = clienteCell.textContent.toLowerCase();
                if (cliente.includes(filter)) {
                    rows[i].style.display = "";
                }
                else {
                    rows[i].style.display = "none";
                }
            }
        }
    }
    function confirmDelete() {
        return confirm("Tem certeza que deseja apagar o registro?");
    }
</script>
<div>
    <input type="text" id="searchInput" onkeyup="searchTable()" placeholder="Pesquisar Transportador" class="form-control" style="width: 300px;">
</div>
<div class="container">
    <a href="@Url.Action("DownloadRelatorio", "Dados")">

        <button id="gerarRelatorio">Relatório em PDF</button>
    </a>

    <p>
        <br />
        <a class="btn btn-primary" id="novoRegistro" asp-action="Create">Criar Novo Registro</a>
    </p>
    <h1>Relatório dos Transportadores</h1>
    <p>Quantidade de transportadores registrados: <span id="totalTransportadores">0</span></p>
    <table class="table" id="pesquisarTransportador">
        <thead>
            <tr>
                <th>
                    Nome Completo
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apelido)
                </th>
                <th>
                    CPF
                </th>
                <th>
                    Data de Nascimento
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prefixo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Bairros)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Veiculo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Placa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ano)
                </th>
                <th>
                    CNH
                </th>
                <th>
                    Categoria
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Validade)
                </th>
                <th>
                    Endereço
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Bairro)
                </th>
                <th>
                    CEP
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Número)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Complemento)
                </th>
                <th>
                    Escolas
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="tabelaTransportadores">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeCompleto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apelido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cpf)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data_Nascimento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefone)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Prefixo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bairros)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Veiculo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Placa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ano)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cnh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoriaSelecionada)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Validade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Endereco)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bairro)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cep)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Número)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Complemento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EscolasSelecionadas)
                    </td>




                </tr>
            }
        </tbody>
    </table>
</div>